version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres:14.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5000:5000"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
