name: Build server container

on:
  push:
    branches:
      - "main"
      - "development"

  # jobs:
  #   docker:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Set up QEMU
  #         uses: docker/setup-qemu-action@v2

  #       - name: Set up Docker Buildx
  #         uses: docker/setup-buildx-action@v2

  #       - name: Login to Docker Hub
  #         uses: docker/login-action@v2
  #         with:
  #           username: ${{ secrets.DOCKERHUB_USERNAME }}
  #           password: ${{ secrets.DOCKERHUB_TOKEN }}

  #       - name: Build and push
  #         uses: docker/build-push-action@v3
  #         with:
  #           context: "{{defaultContext}}:apps/scratchworks-backend"
  #           push: true
  #           tags: ozahnitko/scratchworks-backend-server:dev-latest

  update_server:
    # needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Update
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key && chmod 600 key
          ls -la
          ssh -o StrictHostKeyChecking=no -i key ubuntu@ec2-54-234-149-176.compute-1.amazonaws.com "
            ls -la
          "
