name: Update Scratchworks server

on:
  push:
    branches:
      - "development"

jobs:
  docker:
    name: Build images
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: SEC
        env:
          SECRET: ${{ secrets.SECRET }}
          run: |
            echo ${SECRET}

      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          SECRET: ${{ secrets.SECRET }}
        with:
          context: "{{defaultContext}}:apps/scratchworks-backend"
          push: true
          tags: ozahnitko/scratchworks-backend-server:dev-latest

  update_server:
    name: Update server
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Update
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_KEY" > key && chmod 600 key
          ls -la
          ssh -o StrictHostKeyChecking=no -i key ${USERNAME}@${SERVER_HOST} "
            docker pull ozahnitko/scratchworks-backend-server:dev-latest &&
            docker stop scratchworks-backend-server &&
            docker rm scratchworks-backend-server &&
            docker run -d --name scratchworks-backend-server --network container:postgres ozahnitko/scratchworks-backend-server:dev-latest &&
            docker image prune --force
          "
